name: Deploy

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Deploy to server
        uses: appleboy/ssh-action@master
        with:
          host: "18.130.248.177"
          username: "ubuntu"
          port: 22
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: "cd /var/www/clafiya && ./.scripts/deploy.sh"
